image: 'ruby:2.6'

stages:
  - testing
  - build
  - deploy

before_script:
  - gem install bundler
  - bundle install --path vendor/bundle

cache:
  paths:
    - vendor/bundle

scss-lint:
  type: test
  stage: testing
  environment: testing
  script:
    - bundle exec rake 'scss_lint[--format, Stats]'

build:
  stage: build
  script:
    - bundle exec rake build
  artifacts:
    paths:
      - compiled/
    expire_in: 30 days
  tags:
    - ruby
  only:
    - tags@valeth/wanikani-breeze-dark

pages:
  stage: deploy
  dependencies:
    - build
  script:
    - mv compiled/ public/
  artifacts:
    paths:
      - public
  only:
    - tags@valeth/wanikani-breeze-dark
